---
- name: Ensure supported OS
  ansible.builtin.assert:
    that:
      - ansible_os_family in ['Debian', 'RedHat']
    fail_msg: "This playbook only supports Debian and RedHat based systems."
  run_once: true

- name: Install prereqs
  become: true
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - jq
      - sudo
    update_cache: true
    install_recommends: no

- name: Install prereqs
  become: true
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'Amazon' and
    ansible_distribution_version == '2' and
    ansible_python_version is ansible.builtin.version('2.7', '<=')
  ansible.builtin.yum:
    name:
      - ca-certificates
      - curl
      - jq
      - sudo
    state: latest

- name: >
    Install via command on Amazon Linux 2 due to a lack of dnf, and
    that ansible.builtin.yum only works with python 2.7
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'Amazon' and
    ansible_distribution_version == '2' and
    ansible_python_version is ansible.builtin.version('2.7', '>')
  ansible.builtin.command:
    cmd: yum -y install ca-certificates curl jq sudo
  become: true

- name: Install prereqs
  become: true
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'Amazon' and
    ansible_distribution_version == '2023'
  ansible.builtin.dnf:
    name:
      - ca-certificates
      - curl
      - jq
      - sudo
    state: latest
    # Necessary due to curl/curl-minimal. skip_broken wasn't sufficient
    allowerasing: true
